### PR TITLE
Could upstream be merged into this fork?

### PR DESCRIPTION
**Pull request by devedse**
Hi Pechy,

Could you possibly merge upstream back into this branch as there's also been some performance improvements happening there.

### CODE REVIEW

**Comment by the-crypt-keeper** [comment]
It looks like this has been done in https://github.com/struxoje/chiapos/commits/main but I have not tried it

**Comment by devedse** [comment]
Ok thanks :)

**Comment by grayfallstown** [comment]
Well, I would still like this to be merged here before @pechy does more optimization @struxoje just does not have in his/her repo.

**Comment by pechy** [comment]
Hi, I now rebased on top of upstream (instead of merging, should make merge requests for official chiapos easier). On both main and combined branches.

**Comment by AlanMtX** [comment]
Hi Pechy, you forgot to deallocate thread_pool ...after finish plotting seems 4 thread are active in system
in chiapos.cpp you call thread_pool pool(4);
where you close these threads?
thanks.

**Comment by pechy** [comment]
> Hi Pechy, you forgot to deallocate thread_pool ...after finish plotting seems 4 thread are active in system
> in chiapos.cpp you call thread_pool pool(4);
> where you close these threads?
> thanks.

Hi, this happens automatically when the plotting is finished: https://github.com/pechy/chiapos/blob/main/src/thread_pool.hpp#L57
When the thread pool goes out of scope, threads are stopped and joined.
And the thread_pool is now static, static variables are destructed just before the program exits.

**Pull request closed without merging**
